# Generated by Django 5.2.14 on 2026-05-23 20:17

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sport', models.CharField(default='football', max_length=50)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('starts_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programado'), ('LIVE', 'En vivo'), ('FINISHED', 'Finalizado'), ('SUSPENDED', 'Suspendido'), ('VOIDED', 'Anulado')], default='SCHEDULED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('market_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('SUSPENDED', 'Suspendido'), ('CLOSED', 'Cerrado'), ('SETTLED', 'Liquidado')], default='OPEN', max_length=20)),
                ('margin', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='events.event')),
            ],
            options={
                'unique_together': {('event', 'market_type')},
            },
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('outcome', models.CharField(max_length=50)),
                ('odds', models.DecimalField(decimal_places=4, max_digits=18)),
                ('result', models.CharField(choices=[('PENDING', 'Pendiente'), ('WON', 'Ganó'), ('LOST', 'Perdió'), ('VOID', 'Anulado')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='events.market')),
            ],
        ),
        migrations.CreateModel(
            name='OddsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odds_before', models.DecimalField(decimal_places=4, max_digits=18)),
                ('odds_after', models.DecimalField(decimal_places=4, max_digits=18)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odds_changes', to=settings.AUTH_USER_MODEL)),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds_history', to='events.selection')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
