# Generated by Django 5.2.14 on 2026-05-23 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='margin',
        ),
        migrations.DeleteModel(
            name='OddsHistory',
        ),
    ]
