# Generated by Django 5.2.14 on 2026-05-23 21:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_market_margin_delete_oddshistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OddsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odds_before', models.DecimalField(decimal_places=4, max_digits=18)),
                ('odds_after', models.DecimalField(decimal_places=4, max_digits=18)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odds_changes', to=settings.AUTH_USER_MODEL)),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds_history', to='events.selection')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
