# Generated by Django 5.2.14 on 2026-05-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dni',
            field=models.CharField(blank=True, default=None, max_length=9, null=True, unique=True),
        ),
    ]
