# Generated by Django 5.2.14 on 2026-05-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dni',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
