# Generated by Django 5.2.14 on 2026-05-23 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_limit', models.DecimalField(decimal_places=4, max_digits=18)),
                ('pending_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('pending_since', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='depositlimit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
