# Generated by Django 5.2.14 on 2026-05-27 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_depositlimit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('VELOCITY', 'Alta Velocidad de Transacciones'), ('VARIANCE', 'Varianza Anormal de Monto')], max_length=20)),
                ('description', models.TextField(help_text='Detalle técnico del motivo por el cual se disparó la alerta.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
