# Generated by Django 5.2.14 on 2026-05-23 17:01

import config.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaccion', 'verbose_name_plural': 'Transacciones'},
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='direction',
            field=models.CharField(choices=[('DEBIT', 'Debito (-)'), ('CREDIT', 'Credito (+)')], max_length=6),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='kind',
            field=models.CharField(choices=[('RECHARGE', 'Recarga de fichas'), ('BET_LOCK', 'Bloqueo por apuesta'), ('SETTLEMENT', 'Liquidacion de apuesta')], max_length=15),
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', config.fields.MoneyField(decimal_places=4, max_digits=18)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ACCEPTED', 'Aceptada'), ('WON', 'Ganada'), ('LOST', 'Perdida'), ('CANCELLED', 'Cancelada')], default='ACCEPTED', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lock_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bet', to='wallet.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Apuesta',
                'verbose_name_plural': 'Apuestas',
            },
        ),
    ]
