# Generated by Django 5.2.14 on 2026-05-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='kind',
            field=models.CharField(choices=[('RECHARGE', 'Recarga de fichas'), ('BET_LOCK', 'Bloqueo por apuesta'), ('SETTLEMENT', 'Liquidacion de apuesta'), ('WITHDRAW', 'Retiro de fichas')], max_length=15),
        ),
    ]
